default: &default
  adapter:  postgresql
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:  5000
  encoding: unicode

development:
  <<: *default
  database: robertingrum_development

test:
  <<: *default
  database: robertingrum_test

production:
  <<: *default
  database: robertingrum
